// Purpose: Two-pass, non-generative critique pipeline with byte-exact source citations.
import { readFile, writeFile } from 'node:fs/promises'; import { dirname, join } from 'node:path'; import { fileURLToPath } from 'node:url'; import { estimateCostUsd, estimateTokens } from './jev-client.mjs';
export { createFakeProvider, createJevClient, estimateCostUsd, estimateTokens } from './jev-client.mjs';
const ROOT=dirname(dirname(fileURLToPath(import.meta.url)));
export function splitSpans(text){if(typeof text!=='string')throw new TypeError('text must be a string');const spans=[];const re=/(?:^|\n)[ \t]*(?:[-*•]|\d+[.)])[ \t]+[^\n]+|[^.!?\n]+(?:[.!?]+(?=\s|$)|$)/gm;for(const match of text.matchAll(re)){const raw=match[0];const leading=raw.length-raw.trimStart().length;const value=raw.trim();if(!value)continue;const start=match.index+leading;spans.push({id:`s${spans.length+1}`,text:value,start,end:start+value.length});}return spans;}
export function validatePack(pack){if(!pack?.id||!pack?.title||!Array.isArray(pack.dimensions)||!pack.dimensions.length)throw new TypeError('pack requires id, title and dimensions');const ids=new Set();for(const d of pack.dimensions){if(!d.id||ids.has(d.id)||!d.label||!['score','noul'].includes(d.type)||!d.instructions)throw new TypeError('each dimension requires a unique id, label, score/noul type and instructions');ids.add(d.id);if(!(Number.isFinite(d.weight)&&d.weight>0&&Number.isFinite(d.weak_below)))throw new TypeError(`dimension ${d.id}: positive weight and weak_below required`);if(d.type==='score'&&(!Array.isArray(d.criteria)||d.criteria.length<2||d.criteria.length>10))throw new TypeError(`dimension ${d.id}: invalid score criteria`);}return pack;}
export async function loadPack(value){const path=value.includes('/')||value.endsWith('.json')?value:join(ROOT,'packs',`${value}.json`);return validatePack(JSON.parse(await readFile(path,'utf8')))}
function question(d){return{type:d.type,instructions:d.instructions,...(d.criteria?{criteria:d.criteria}:{})}}
export function normalized(answer,d){return answer.type==='noul'?answer.noul:answer.score/(d.criteria.length-1)}
export function compositeScore(results,pack){let total=0,weights=0;for(const d of pack.dimensions){total+=normalized(results[d.id],d)*d.weight;weights+=d.weight;}return weights?total/weights:0}
function keywords(text){return new Set(text.toLowerCase().match(/[a-z]{4,}/g)||[])}
export function selectCandidates(spans,instructions,limit=255){if(spans.length<=limit)return spans;const keys=keywords(instructions);return spans.map((span,index)=>({span,rank:[...keywords(span.text)].filter(k=>keys.has(k)).length*100+Math.min(span.text.length,160)-index/1000})).sort((a,b)=>b.rank-a.rank).slice(0,limit).sort((a,b)=>a.span.start-b.span.start).map(x=>x.span)}
export function estimateRoast(text,pack){const spans=splitSpans(text);const passOne=estimateTokens({state:text,questions:Object.fromEntries(pack.dimensions.map(d=>[d.id,question(d)]))});const candidates=selectCandidates(spans,pack.dimensions.map(d=>d.instructions).join(' '));const passTwo=pack.dimensions.reduce((sum,d)=>sum+estimateTokens({state:text,questions:{[d.id]:{type:'choice',instructions:d.instructions,criteria:Object.fromEntries(candidates.map(s=>[s.id,null]))}}}),0);return{maximumRequests:1+pack.dimensions.length,estimatedInputTokens:passOne+passTwo,estimatedCostUsd:estimateCostUsd(passOne+passTwo),candidateCount:spans.length}}
export async function roast({text,pack,provider}){validatePack(pack);const spans=splitSpans(text);const first=await provider({state:text,questions:Object.fromEntries(pack.dimensions.map(d=>[d.id,question(d)]))});const weak=pack.dimensions.filter(d=>normalized(first.answers[d.id],d)<d.weak_below);const citations={};const secondPass=[];for(const d of weak){const candidates=selectCandidates(spans,d.instructions);if(!candidates.length)continue;const criteria=Object.fromEntries(candidates.map(s=>[s.id,null]));const response=await provider({state:text,questions:{[d.id]:{type:'choice',instructions:`Which source span best illustrates this weakness: ${d.instructions}`,criteria}}});const chosen=candidates.find(s=>s.id===response.answers[d.id].choice);if(chosen)citations[d.id]=chosen;secondPass.push(response)}const inputTokens=first.usage.input_tokens+secondPass.reduce((n,r)=>n+r.usage.input_tokens,0);return{pack:pack.id,model:first.model,score:compositeScore(first.answers,pack),dimensions:first.answers,citations,source:text,usage:{input_tokens:inputTokens,estimated_cost_usd:estimateCostUsd(inputTokens)}}}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function renderHtml(report,pack){const rows=pack.dimensions.map(d=>{const v=normalized(report.dimensions[d.id],d);const c=report.citations[d.id];return`<article><h2>${esc(d.label)} <span>${Math.round(v*100)}</span></h2><div class="bar"><i style="width:${v*100}%"></i></div>${c?`<blockquote data-start="${c.start}">${esc(c.text)}</blockquote>`:''}</article>`}).join('');return`<!doctype html><html><head><meta charset="utf-8"><title>${esc(pack.title)} roast</title><style>body{max-width:820px;margin:60px auto;font:18px system-ui;background:#11131a;color:#f8f3e7}h1{font-size:4rem}.bar{height:16px;background:#292f3b}.bar i{display:block;height:100%;background:#ff655c}article{margin:28px 0}h2{display:flex;justify-content:space-between}blockquote{border-left:4px solid #f3bd43;padding:12px;background:#1b202b}</style></head><body><h1>${esc(pack.title)}</h1><p>Composite ${Math.round(report.score*100)}/100</p>${rows}<hr><pre>${esc(report.source)}</pre></body></html>`}
export async function writeReport(report,pack,path){await writeFile(path,renderHtml(report,pack));return path}
